package com.billing.backend.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

/**
 * LoginRequest — the request body for POST /api/auth/login
 *
 * DTO = Data Transfer Object.
 * It's a simple class that holds the data coming in from the HTTP request body.
 * It is NOT stored in the database — it's only used to carry data between
 * the client (Angular) and the controller.
 *
 * @NotBlank → validation annotation: field cannot be null, empty, or whitespace.
 *             If violated, Spring returns a 422 error automatically.
 *
 * The "username" field accepts BOTH a username ("admin") OR an email ("admin@ubs.io").
 * The AuthService checks whether it contains "@" to decide which one it is.
 *
 * captchaToken → the reCAPTCHA v2 token generated by the frontend widget.
 *                Verified server-side by CaptchaService before credentials are checked.
 *                Required when recaptcha.enabled=true in application.properties.
 */
@Data
public class LoginRequest {

    @NotBlank(message = "Please enter your username or email")
    private String username;   // Can be username OR email — matches frontend field name

    @NotBlank(message = "Please enter your password")
    private String password;

    // reCAPTCHA v2 token from the Angular widget (grecaptcha.getResponse())
    // @NotBlank is NOT used here — CaptchaService handles the check so we can
    // return a descriptive 400 rather than a generic 422 validation error.
    private String captchaToken;
}
